
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://WS/", className = "proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://WS/", className = "proxy.ConvertResponse")
    @Action(input = "http://WS/BanqueService/convertRequest", output = "http://WS/BanqueService/convertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://WS/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://WS/", className = "proxy.GetcompteResponse")
    @Action(input = "http://WS/BanqueService/getcompteRequest", output = "http://WS/BanqueService/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listecomptes", targetNamespace = "http://WS/", className = "proxy.Listecomptes")
    @ResponseWrapper(localName = "listecomptesResponse", targetNamespace = "http://WS/", className = "proxy.ListecomptesResponse")
    @Action(input = "http://WS/BanqueService/listecomptesRequest", output = "http://WS/BanqueService/listecomptesResponse")
    public List<Compte> listecomptes();

}
